#ifndef MESSAGE_H
# define MESSAGE_H
// error
# define ERR_TOOMANYCHANNELS(user, channel) "405 " + user + " " + channel + " :You have joined too many channels" + "\r\n"
# define ERR_NONICKNAMEGIVEN(user) "431 " + user + " :No nickname given" + "\r\n"
# define ERR_ERRONEOUSNICKNAME(user, param) "432 " + user + " " + param + " :Erroneous Nickname" + "\r\n"
# define ERR_NICKNAMEINUSE(user) "433 " + user + " " + user + " :Nickname is already in use" + "\r\n"
# define ERR_NEEDMOREPARAMS(source, command) "461 " + source + " " + command + " :Not enough parameters" + "\r\n"
# define ERR_ALREADYREGISTERED(source) "462 " + source + " :You may not register" + "\r\n"
# define ERR_PASSWDMISMATCH(user) "464 " + user + " :Password incorrect" + "\r\n"
# define ERR_NOORIGIN(user) "465 " + user + " :No origin specified" + "\r\n"
# define ERR_CHANNELISFULL(user, channel) "471 " + user + " " + channel + " :Cannot join channel (+1)" + "\r\n"
# define ERR_INVITEONLYCHAN(user, channel) "473 " + user + " " + channel + " :Cannot join channel (+i)" + "\r\n"
# define ERR_BANNEDFROMCHAN(user, channel) "474 " + user + " " + channel + " :Cannot join channel (+b)" + "\r\n"
# define ERR_BADCHANNELKEY(user, channel) "475 " + user + " " + channel + " :Cannot join channel (+k)" + "\r\n"
# define ERR_INVALIDCHANNEL(user_nick, channel) "476 " + user_nick + " " + channel + " :Invalid channel name" + "\r\n"
# define ERR_QUIT(user, message) "ERROR :Closing link: (" + user + ") [Quit: " + message + "]" + "\r\n"
# define ERR_NOSUCHSERVER(user, server) "402 " + user + " " + server + " :No such server" + "\r\n"
# define ERR_NOSUCHCHANNEL(user_nick, channel) "403 " + user_nick + " " + channel + " :No such channel" + "\r\n"
# define ERR_CHANOPRIVSNEEDED(user, channel) "482 " + user + " " + channel + " :You must be a channel operator" + "\r\n"
# define ERR_CHANOPRIVSNEEDED2(user, channel) "482 " + user + " " + channel + " :You must be a channel half-operator" + "\r\n"
# define ERR_CHANOPRIVSNEEDEDMODE(user_nick, channel, mode) "482 " + user_nick + " " + channel + " :You must have channel op access or above to set channel mode " + mode + "\r\n"
# define ERR_USERNOTINCHANNEL(user, nick, channel) "441 " + user + " " + nick + " " + channel + " :They are not on that channel" + "\r\n"
# define ERR_NOTONCHANNEL(user, channel) "442 " + user + " " + channel + " :You're not on that channel!" + "\r\n"
# define ERR_CANNOTSENDTOCHAN(user, channel) "404 " + user + " " + channel + " :Cannot send to channel (no external messages)" + "\r\n"
# define ERR_NOTEXTTOSEND(user_nick) "412 " + user_nick +  " :No text to send" + "\r\n"
# define ERR_NOSUCHNICK(user_nick, nick) "401 " + user_nick + " " + nick + " :No such nick" + "\r\n"
# define ERR_UNKNOWNMODE(user_nick, mode) "472 " + user_nick + " " + mode + " :is an unknown mode character" + "\r\n"
# define ERR_NOOPPARAM(user_nick, channel, mode, modename, param) "696 " + user_nick + " " + channel + " " + mode + " * :You must specify a parameter for the " + modename + " mode. Syntax: <" + param + ">." + "\r\n"
# define ERR_LONGPWD(user, channel) ":" + user + " " + channel + " :Too long password" + "\r\n"
# define ERR_USERONCHANNEL(user, nick, channel) "443 " + user + " " + nick + " " + channel + " :is already on channel" + "\r\n"
// numeric
# define RPL_WELCOME(user) "001 " + user + " :Welcome to the happyirc network " + user + "!" + "\r\n"
# define RPL_TOPIC(user, channel, topic) "332 " + user + " " + channel + " :" + topic + "\r\n"
# define RPL_TOPICWHOTIME(user, channel, nick, setat) "333 " + user + " " + channel + " " + nick + " " + setat + "\r\n"
# define RPL_WHOREPLY(client, channel, user, host, server, nick, opt, real) "352 " + client + " " + channel + " " + user + " " + host + " " + server + " " + nick + " " + opt + " " + ":0 " + real + "\r\n"
# define RPL_ENDOFWHO(user, name) "315 " + user + " " + name + " :End of /WHO list" + "\r\n"
# define RPL_NAMREPLY(user, symbol, channel, users) "353 " + user + " " + symbol + " " + channel + " :" + users + "\r\n"
# define RPL_ENDOFNAMES(user, channel) "366 " + user + " " + channel + " :End of /NAMES list." + "\r\n"
# define RPL_LISTSTART(user) "321 " + user + " Channel :Users Name" + "\r\n"
# define RPL_LIST(user, channel, visible, mode, topic) "322 " + user + " " + channel + " " + visible + " :" + mode + " " + topic + "\r\n"
# define RPL_LISTENED(user) "323 " + user + ":End of /LIST"
# define RPL_NOTOPIC(user, channel) "331 " + user + " " + channel + " :No topic is set" + "\r\n"
# define RPL_INVITING(user, nick, channel) "341 " + user + " " + nick + " :" + channel + "\r\n"
# define RPL_CHANNELMODEIS(user_nick, channel, modes, params) "324 " + user_nick + " " + channel + " " + modes + params + "\r\n"
# define RPL_CHANNELCREATETIME(user, channel, date) "329 " + user + " " + channel + " :" + date + "\r\n"
# define RPL_ENDOFBANLIST(user, channel) "368 " + user + " " + channel + " :End of channel ban list" + "\r\n"
// command
// origin
# define RPL_QUIT(user, message) ":" + user + " QUIT :" + message + "\r\n"
# define RPL_PONG(user, ping) ":" + user + " PONG :" + ping + "\r\n"
# define RPL_JOIN(user, channel) ":" + user + " JOIN :" + channel + "\r\n"
# define RPL_PRIVMSG(user, target, message) ":" + user + " PRIVMSG " + target + " :" + message + "\r\n"
# define RPL_MY_TOPIC(user, channel, topic) ":" + user + " TOPIC " + channel + " :" + topic + "\r\n"
# define RPL_PART(user, channel) ":" + user + " PART "+ channel + "\r\n"
# define RPL_KICK(user, channel, nick, message) ":" + user + " KICK " + channel + " " + nick + " :" + message+ "\r\n"
# define RPL_INVITE(user, nick, channel) ":" + user + " INVITE " + nick + " :" + channel + "\r\n"
# define RPL_MODE(user_pfx, channel, modes, params) ":" + user_pfx + " MODE " + channel + " " + modes + params + "\r\n"
# define RPL_NICK(before, after) ":" + before + " NICK :" + after + "\r\n"

#endif  // MESSAGE_H
